[[images]]
src = "/images/gallery/business_cat.jpg"
alt = "This cat means business"

[[images]]
src = "/images/gallery/face.jpg"
alt = "A picture of a face"

[[images]]
src = "/images/gallery/smoke.jpg"
alt = "Smoke"

[[images]]
src = "/images/gallery/happy_bathtub.jpg"
alt = "A happy bathtub"

[[images]]
src = "/images/gallery/head.jpg"
alt = "A head of its time"

[[images]]
src = "/images/gallery/karl.jpg"
alt = "A drawing of one of my closest friends"

[[images]]
src = "/images/gallery/lola.jpg"
alt = "Drawing of my older sisters dog"

[[images]]
src = "/images/gallery/self_portrait_1.jpg"
alt = "Self Portrait"

[[images]]
src = "/images/gallery/Groovy.jpg"
alt = "Ash Vs Evil Dead"