logo = "images/logo.svg"
colorScheme = "avocado"

[author]
name = "Adam Brykajlo"
image = "images/headshot.jpg"
headline = "Software Engineer in Visual Computing"
links = [
    { github = "https://github.com/abrykajlo" },
    { linkedin = "https://www.linkedin.com/in/abrykajlo/" },
    { email = "mailto:adam.brykajlo@gmail.com" },
]

[footer]
showAppearanceSwitcher = false