title: Adam Brykajlo
email: adam.brykajlo@gmail.com
description: >
  A blog about my adventures in drawing and digital art
  and possibly a foray into webassembly and webgl programming
  in C++.
baseurl: "www.adambrykajlo.ca"
url: "www.adambrykajlo.ca"

author: Adam Brykajlo
linkedin: abrykajlo
github:  abrykajlo
twitter: AdamBrykajlo
ga-property-id: UA-30680897-2

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  style: compressed

collections:
  art:
    output: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
