baseURL = "https://www.adambrykajlo.ca/"
languageCode = "en"
title = "Adam Brykajlo"

googleAnalytics = "G-4LCY6N96TZ"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[services.disqus]
shortname = "abrykajlo"

[caches.images]
dir = ":cacheDir/images"

[markup.goldmark.renderer]
unsafe = true