site_name: Adam Brykajlo
theme:
  name: material
  favicon: images/favicon.svg
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      primary: custom
      accent: custom

extra_css:
  - stylesheets/extra.css

plugins:
  - blog:
      blog_dir: .
  - search
  - tags
  - glightbox